#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	ffmpeg="ffmpeg -hide_banner" \
	less="less +k" \
	du="du -h" \
	df="df -h -x tmpfs -x devtmpfs" \
	ect="ect --mt-file --mt-deflate -progressive" \
	leanify="leanify --keep-exif -p" \
	lsblk="lsblk -o NAME,FSTYPE,PARTLABEL,FSUSED,SIZE,MOUNTPOINT" \
	parallel="parallel --bar" \
	duperemove="sudo duperemove --hashfile=${XDG_CACHE_HOME:-$HOME/.cache}/duperemove-hashfile -hrdq" \
	jdupes="jdupes -M" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	zstd="zstd -T0" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ip="ip -color=auto"

# Use exa for ls if present
[ -x "$(command -v exa)" ] && alias ls="exa -hg --group-directories-first"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	trem="transmission-remote" \
	f="lf" \
	v="$EDITOR" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	lsps="expac -H M \"%m %n\" | sort -nr | less" \
	cpc="removeorphans" \
	trem="transmission-remote" \
	x="sxiv -ft *" \

alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	btm="btm -g --color gruvbox --mem_as_value" \

fv() { fzf | xargs -r -I % $EDITOR % ;}
fl() { fzf | xargs -ro -I % lf % ; }
fx() { fzf | xargs -r -I % xdg-open % ; }
mkcd() { mkdir -pv $1 && cd $1 ; }
vp() { which "$@" | xargs -d "\n" nvim -p ; }
cdp() { cd $(dirname $(which "$1")) ; }

dic() { sdcv -n "$1" | w3m -T text/html ; }

fmnt() { mount -o uid=$(id -u),gid=$(id -g) "$@" }
