#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for x in mount umount sv pacman updatedb su ; do
	alias $x="sudo $x"
done

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	less="less +k" \
	du="du -h" \
	df="df -h -x tmpfs -x devtmpfs" \
	ect="ect --mt-file -progressive" \
	pdfo="pdfsizeopt --use-multivalent=YES" \
	lsblk="lsblk -o NAME,FSTYPE,PARTLABEL,SIZE,FSUSED,MOUNTPOINT" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --style=pablo --out-format=ansi --force" \

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="lf" \
	lf="lf-img"\
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	lsps="expac -H M \"%m %n\" | sort -nr | less" \
	cpc="removeorphans" \
	SS="sudo systemctl" \
	g="git" \
	gua="git remote | xargs -L1 git push --all" \
	trem="transmission-remote" \
	x="sxiv -ft *" \
	yt="youtube-dl --add-metadata -i -o '%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
   	odmnt="rclone --vfs-cache-mode writes mount onedrive: $HOME/odmnt &" \
	odjnl="journalctl --user-unit onedrive -f" \
	odstart="systemctl --user start onedrive" \
	odoff="systemctl --user stop onedrive" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura" \

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	btm="btm -g --color gruvbox --mem_as_value" \

fv() { fzf | xargs -r -I % $EDITOR % ;}
fd() { find $HOME/Documents/ | fzf | xargs -ro -I % lf % ; }
fl() { fzf | xargs -ro -I % lf % ; }
fx() { fzf | xargs -r -I % xdg-open % ; }
mkcd() { mkdir -pv $1 && cd $1 ; }
vp() { which "$@" | xargs -d "\n" nvim -p ; }
cdp() { cd $(dirname $(which "$1")) ; }

dic() { sdcv -n "$1" | w3m -T text/html ; }
