#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	bat="cat /sys/class/power_supply/BAT?/capacity" \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	less="less +k"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --style=pablo --out-format=ansi --force" \
	td="todoist --color"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	mkd="mkdir -pv" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	cpc="removeorphans" \
	SS="sudo systemctl" \
	g="git" \
	gua="git remote | xargs -L1 git push --all" \
	trem="transmission-remote" \
	clean="find ./ -regex \"\(.*archtop.*\)\|\(.*\.tex$\)\" -exec rm '{}' \;" \
	x="sxiv -ft *" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
     	odmnt="rclone --vfs-cache-mode writes mount onedrive: $HOME/odmnt &" \
	odjnl="journalctl --user-unit onedrive -f" \
	odstart="systemctl --user start onedrive" \
	odoff="systemctl --user stop onedrive" \
	enc="gpg --no-symkey-cache -c" \
	dec="gpg --no-symkey-cache -d" \
	tdq="printf \"Quick-add task: \"; read task && todoist q \"#Agenda \$task\"" \
	tds="todoist --color show \$(todoist list | dmenu -l 20 | cut -d ' ' -f 1)" \
	tdc="todoist --color close \$(todoist list | dmenu -l 20 | cut -d ' ' -f 1)"

# Start certain programs with wrapper scripts
alias \
	calcurse="startcal" \
	diff="diff --color=auto" \
	emacs="startemacs"

# This alias requires zsh and .local/zshscripts/pty.zsh
alias tdl="pty todoist --color list | less"

# This alias is important. It enables the `pauseallmpv` command.
alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"

# Some other stuff
alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
	weath="less -S ~/.local/share/weatherreport"

vf() { fzf | xargs -r -I % $EDITOR % ;}
