#!/usr/bin/env sh
alias ka="killall" \
	mkd="mkdir -pv" \
	magit="nvim -c MagitOnly" \
	SS="sudo systemctl" \
	f="$FILE" \
	g="git" \
	gua="git remote | xargs -L1 git push --all" \
	trem="transmission-remote" \
	p="sudo pacman" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	cpc="removeorphans" \
	clean="find ./ -regex \"\(.*archtop.*\)\|\(.*\.tex$\)\" -exec rm '{}' \;" \
	e="$EDITOR" \
	v="$EDITOR" \
	x="sxiv -ft *" \
	sdn="sudo shutdown -h now" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
	ccat="highlight --style=pablo --out-format=ansi --force" \
	ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
     	odmnt="rclone --vfs-cache-mode writes mount onedrive: $HOME/odmnt &" \
	odjnl="journalctl --user-unit onedrive -f" \
	odstart="systemctl --user start onedrive" \
	odoff="systemctl --user stop onedrive" \
	enc="gpg --no-symkey-cache -c" \
	dec="gpg --no-symkey-cache -d" \
	td="todoist --color" \
	tdq="printf \"Quick-add task: \"; read task && todoist q \"#Agenda \$task\"" \
	ls="ls -hN --color=auto --group-directories-first" \
	less="less +k" \
	grep="grep --color=auto" \
	ffmpeg="ffmpeg -hide_banner" \
	mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)" \
	calcurse="startcal" \
	diff="diff --color=auto" \
	lf="lfifo"

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() { fzf | xargs -r -I % $EDITOR % ;}

manualinstall() { # Installs $1 manually if not installed.
[ -f "/usr/bin/$1" ] || (
cd /tmp || exit
rm -rf /tmp/"$1"*
curl -sO https://aur.archlinux.org/cgit/aur.git/snapshot/"$1".tar.gz &&
tar -xvf "$1".tar.gz >/dev/null 2>&1 &&
cd "$1" &&
makepkg --noconfirm -si
cd /tmp || return) ;}

