#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	less="less +k" \
	du="du -h" \
	df="df -h"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --style=pablo --out-format=ansi --force" \
	td="todoist --color"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	mkd="mkdir -pv" \
	f="lf" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
	lsp="pacman -Qett --color=always | less" \
	lsps="expac -H M \"%m %n\" | sort -nr | less" \
	cpc="removeorphans" \
	SS="sudo systemctl" \
	g="git" \
	gua="git remote | xargs -L1 git push --all" \
	trem="transmission-remote" \
	x="sxiv -ft *" \
	yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
	yta="yt -x -f bestaudio/best" \
	YT="youtube-viewer" \
   	odmnt="rclone --vfs-cache-mode writes mount onedrive: $HOME/odmnt &" \
	odjnl="journalctl --user-unit onedrive -f" \
	odstart="systemctl --user start onedrive" \
	odoff="systemctl --user stop onedrive" \
	tdq="printf \"Quick-add task: \"; read task && todoist q \"#Agenda \$task\"" \
	tds="todoist --color show \$(todoist list | dmenu -l 20 | cut -d ' ' -f 1)" \
	tdc="todoist --color close \$(todoist list | dmenu -l 20 | cut -d ' ' -f 1) &"
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

# Start certain programs with wrapper scripts
alias \
	calcurse="startcal" \
	emacs="startemacs"

# This alias requires zsh and .local/zshscripts/pty.zsh
alias tdl="pty todoist --color list | less"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \

fv() { fzf | xargs -r -I % $EDITOR % ;}
fd() { find $HOME/Documents/ | fzf | xargs -r -I % $FILE % ; }
fx() { fzf | xargs -r -I % setsid -f xdg-open % >/dev/null 2>&1 ; }
